"""Regenerates the Peel-It logo and mascot drawables, plus PNG previews.

    python3 tools/brand/make.py            # writes app/src/main/res/drawable/{ic_launcher_*,mascot}.xml
    NODE_PATH=$(npm root -g) node tools/brand/render.js tools/brand/out/logo.svg logo.png 512

The shapes live in flat.py: one flat side-view elephant (a lady, with a pink ear and bow), shown on
a peeling sticker for the launcher icon and on her own, lifting a sticker, as the mascot. vd.py
turns them into both SVG (for previews) and VectorDrawable XML.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from flat import BG, logo, mascot  # noqa: E402
from vd import svg, vector  # noqa: E402

RES = os.path.join(HERE, "..", "..", "app", "src", "main", "res", "drawable")
OUT = os.path.join(HERE, "out")


def main():
    os.makedirs(OUT, exist_ok=True)
    files = {
        "ic_launcher_foreground.xml": vector(logo(), 108, 108, 108, 108,
            "Peel-It: the elephant mascot on a sticker whose corner is peeling. Kept inside the 66dp safe\n"
            "     circle so every launcher mask shows it whole. Generated by tools/brand (make.py);\n"
            "     edit the shapes there rather than here."),
        "ic_launcher_monochrome.xml": vector(logo("mono"), 108, 108, 108, 108,
            "Themed-icon silhouette of the logo (Android 13+ tints it). Generated by tools/brand."),
        "mascot.xml": vector(mascot(), 200, 200, 200, 200,
            "The Peel-It mascot: a lady elephant lifting a sticker with her trunk. Generated by\n"
            "     tools/brand; edit the shapes there rather than here."),
    }
    for name, text in files.items():
        with open(os.path.join(RES, name), "w") as f:
            f.write(text)
    with open(os.path.join(OUT, "logo.svg"), "w") as f:
        f.write(svg(logo(), 108, 108, BG))
    with open(os.path.join(OUT, "mascot.svg"), "w") as f:
        f.write(svg(mascot(), 200, 200))
    print("Wrote", ", ".join(files), "and SVG previews in tools/brand/out")


if __name__ == "__main__":
    main()
